# Generated by Django 5.0.7 on 2024-07-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabsOnlineForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=250)),
                ('customer_email', models.EmailField(max_length=254)),
                ('mo_no', models.IntegerField()),
                ('cab_type', models.CharField(max_length=100)),
                ('from_destination', models.CharField(max_length=200)),
                ('to_destination', models.CharField(max_length=200)),
                ('datetime', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
