# Generated by Django 5.0.7 on 2024-07-23 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parmarcabapp', '0002_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabsonlineform',
            name='journey_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
