# Generated by Django 5.0.7 on 2024-07-23 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parmarcabapp', '0003_cabsonlineform_journey_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabsonlineform',
            name='journey_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
