# Generated by Django 5.0.7 on 2024-07-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parmarcabapp', '0004_cabsonlineform_journey_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabsonlineform',
            name='journey_date',
            field=models.CharField(max_length=50),
        ),
    ]
